### ISSUE TITLE
[Volunteer] < Enhance apache shenyu unit test >

### ISSUE THREAD

**Issue by songyuequan** [apache/shenyu#2420]
### Volunteer help
Hi Community:
you can see the unit test Coverage in  https://app.codecov.io/gh/apache/incubator-shenyu
or  target/site/index.html  under each module in your local enviroment.
and there are some tasks to improve the unit test Coverage.
let's improve the coverage of unit test  together !

- [x] ISSUE #2236  @haibo-duan
- [x] ISSUE #2144   @haibo-duan
- [x] ISSUE #2139  @haibo-duan 
- [ ] ISSUE #2136  @AhahaGe  blocking
- [ ] ISSUE #2078 @tonytanCoder and the pr is https://github.com/apache/incubator-shenyu/pull/2166  plz check ci
- [ ] ISSUE #2080  @yangtianrui95 

------
- [ ] ISSUE #2404  (Coverage 64.71%) @zhaiweij 
- [ ] ISSUE #1824    (Coverage 75.12%)  @haibo-duan  doing
- [ ] ISSUE #1458     (Coverage 71.05%)  @haibo-duan
- [ ] ISSUE #1456    (Coverage 29.58%)  @plutokaito 
- [ ] shenyu-common   (Coverage 29.79%) 
- [ ] shenyu-register-center  (Coverage 44.32%)

**Comment by AhahaGe** [comment]
please assign ConsulClientRegisterRepository to me

**Comment by plutokaito** [comment]
let me try Enhance shenyu-web module unit test.

**Comment by songyuequan** [comment]
> let me try Enhance shenyu-web module unit test.

thank you  for your help.

**Comment by AhahaGe** [comment]
ConsulClientRegisterRepository #2136 meet some problem, can't start example with consul register center.

**Comment by AhahaGe** [comment]
Can u assign some other test case to me?

**Comment by haibo-duan** [comment]
please assign these issue to me:
ISSUE [Volunteer] Add unit test for ShenyuClientRegisterTarsServiceImpl #2144
ISSUE [Volunteer] Add unit test for ShenyuClientRegisterGrpcServiceImpl #2139

**Comment by songyuequan** [comment]
> please assign these issue to me: ISSUE [Volunteer] Add unit test for ShenyuClientRegisterTarsServiceImpl #2144 ISSUE [Volunteer] Add unit test for ShenyuClientRegisterGrpcServiceImpl #2139

Hi ,I have assign these to you.  thank you

**Comment by haibo-duan** [comment]
Please assign these tasks to me:
ISSUE shenyu-admin module test coverage improvement #1824 (Coverage 72.37%)
 ISSUE Enhance shenyu-sync-data-center module unit test #1458 (Coverage 71.05%)

**Comment by songyuequan** [comment]
> Please assign these tasks to me: ISSUE shenyu-admin module test coverage improvement #1824 (Coverage 72.37%) ISSUE Enhance shenyu-sync-data-center module unit test #1458 (Coverage 71.05%)

Ok, thank you for your help .
