### ISSUE TITLE
[GSoC 2022] Integration tests cover more scenarios

### ISSUE THREAD

**Issue by JooKS-me** [apache/shenyu#2890]
### Description

Shenyu already has a relatively complete integration testing framework, but some plug-ins have not been tested, such as oathu2 plugin, cache plugin, metrics plugin, log-rockermq plugin, and etc.

### Task List

- [ ] Complete the integration test of the Oauth2 plugin
- [x] Complete the integration test of the cache plugin
- [x] Complete the integration test of the metrics plugin
- [x] Complete the integration test of the log-rocketmq plugin
- [ ] And more, if you want.

### Recommended Skills

Familiar with Java

Know the usage of spring-framework

Have some knowledge about Docker

### Mentor

Kunshuai Zhu, Committer of Apache ShenYu, https://github.com/JooKS-me, [jooks@apache.org](mailto:jooks@apache.org)

**Comment by kaveeshadinamidu** [comment]
@JooKS-me  I would like to contribute to this project on GSoC 2022. Can you give me guide me on how should I start with the project? Thank You!

**Comment by JooKS-me** [comment]
@kaveeshadinamidu Welcome~

This project has roughly two lines: helm charts and integration tests (or e2e test). 

For helm charts, you need to try to [deploy shenyu-boostrap and shenyu-admin in Kubernetes](https://shenyu.apache.org/docs/next/deployment/deployment-k8s), then learn helm and how to write helm charts.

For integration testing, take a look at the existing [integration testing framework](https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test) and [this blog](https://shenyu.apache.org/blog/IntegrationTest-Analysis) .

But before that, I recommend you to start with [documentation](https://shenyu.apache.org/docs/next/index) to understand Apache-ShenYu and run at least some examples.

**Comment by kaveeshadinamidu** [comment]
Okay, thank you @JooKS-me . I will look at them and try my best to work on them. 
Thank you!

**Comment by yu199195** [comment]
Looks very good~

**Comment by erdengk** [comment]
Wow, such an excellent project, I also want to contribute.

**Comment by kapilaNR** [comment]
@yu199195  I would like to contribute to this project in 2022 GSoC.

**Comment by ashu665665** [comment]
@yu199195 I would like to contribute to this project.
