### ISSUE TITLE
[GSoC 2022] Add logging-elasticsearch plugin

### ISSUE THREAD

**Issue by yu199195** [apache/shenyu#2896]
## Description

add logging-elasticsearch plugin, it Use elasticsearch to store shenyu's logs.
Take the shenyu gateway log information, write it to elasticSearch and display it.

Can add module like this ：
               shenyu-plugin
               ------ shenyu-plugin-logging-elasticsearch

## Task

- [ ] Add shenyu-plugin-logging-elasticsearch module and impl write it to elasticSearch
- [ ] Complete unit test for this module
- [ ] Complete the integration for this module
- [ ] Complete doc for this module in shenyu website 

### Recommended Skills

Familiar with Java and reactor Java

Know the usage of  shenyu plugin ecology 

Know the usage of elasticSearch java client

Have some knowledge about  Docker

### Mentor

XiaoYu, PPMC of Apache ShenYu, https://github.com/yu199195, [xiaoyu@apache.org](mailto:xiaoyu@apache.org)

**Comment by QinHaiqi** [comment]
Hi~My name is Qin Haiqi. I majored in computer science at Northeastern University.I would like to contribute to this project on GSoC 2022~

**Comment by QinHaiqi** [comment]
Hi\~My name is Qin Haiqi. I majored in computer science at Northeast University.I would like to contribute to this project on GSoC 2022~

**Comment by DevGautam2000** [comment]
I would like to contribute to this project for GSOC 2022. Would you kindly provide with further details Sir?

**Comment by yu199195** [comment]
@DevGautam2000  hi，you can see this ： [subscribe-email](https://shenyu.apache.org/community/subscribe-email/),

[code-suggestions](https://shenyu.apache.org/community/code-suggestions) and [how to contributor](https://shenyu.apache.org/community/contributor)

**Comment by DevGautam2000** [comment]
> @DevGautam2000 hi，you can see this ： [subscribe-email](https://shenyu.apache.org/community/subscribe-email/),
> 
> [code-suggestions](https://shenyu.apache.org/community/code-suggestions) and [how to contributor](https://shenyu.apache.org/community/contributor)

Sure I will check it out. Thank you, SIr

**Comment by yu199195** [comment]
update doc is ：

https://shenyu.apache.org/community/contributor-guide 
https://shenyu.apache.org/community/issue-pr
https://shenyu.apache.org/community/code-suggestions

**Comment by kapilaNR** [comment]
@yu199195  I would like to contribute to this project for GSoC 2022. Is this still open to contribution?

**Comment by yu199195** [comment]
@kapilaNR  hi， It is open and if you are interested, you are welcome to participate~
