### ISSUE TITLE
[GSoC 2022] Shenyu add logging-kafka plugin

### ISSUE THREAD

**Issue by tuohai666** [apache/shenyu#2917]
## Description

Add logging-kafka plugin, it Use Kafka to store shenyu's logs.
Take the shenyu gateway log information, write it to Kafka and display it.
Can add module like this ：
shenyu-plugin
  - shenyu-plugin-logging-kafka

## Task

- [ ] Add shenyu-plugin-logging-kafka module and impl write it to kafka
- [ ] Complete unit test for this module
- [ ] Complete the integration for this module
- [ ] Complete doc for this module in shenyu website 

### Recommended Skills

Familiar with Java

Know the usage of shenyu plugin ecology

Know the usage of Kafka java client

Have some knowledge about  Docker

### Mentor

Zhang Yonglun, PPMC of Apache ShenYu, https://github.com/tuohai666, [zhangyonglun@apache.org](mailto:zhangyonglun@apache.org)

**Comment by erdengk** [comment]
@hutaishi  Fortunately, gsoc lifted the restrictions this year. Any adult can participate in the gsoc.

**Comment by gaochuang98** [comment]
This is really good news , can i get involved ？

**Comment by qifanyyy** [comment]
Hi, I also would like to contribute my time and effort to this feature if possible.

**Comment by itwaiX** [comment]
I have used Java and kafka and am very interested in it and want to participate in the project

**Comment by selectbook** [comment]
I would like to contribute to this feature if possible.

**Comment by mehrdadmoradii** [comment]
Hi, I'm Mehrdad, currently in the second year of the Software Engineering program at Centennial College (Toronto, Canada).
I would like to kickstart my open-source development journey with ASF and GSoC.

The following is a summary of my skills and qualifications:

- Data Structures and Algorithm design.
- Java, Maven, and IntelliJ.
- Spring Framework and its community (Spring Boot, Spring Security, Spring Data, and HATEOAS).
- Microservices and RESTful architecture.
- HTTP, SSL, SSH, and WebSocket.
- Comfortable working in Unix/Linux environment and Git.
- Passionate about open-source community.

**Comment by yu199195** [comment]
@mehrdadmoradii 

hi, You have very good skills and look forward to your participation GSoc 2022

**Comment by mehrdadmoradii** [comment]
@yu199195 Hi Xiaoyu, thanks for your response. I will submit the proposal. 

I am looking forward to working with you.

**Comment by homihq** [comment]
What is the rationale for logging into Kafka? 
Is there any specific scenario where this is useful?
