### ISSUE TITLE
[Task] New feature Cache Plugin

### ISSUE THREAD

**Issue by qicz** [apache/shenyu#3123]
### Description

The response data for configured requests can be cached and returned directly from the gateway next time.

### Task List

- [x]  Cache Plugin Module @qicz 
- [x]  Cache Plugin & test @qurenneng 
- [x]  Cache Write Plugin & test @zouchangfu 
- [x]  Memory Cache (spi) & test @qicz  @zhouyadong 
- [x]  Redis Cache (spi) & test @zhouyadong  @qicz 
- [x]  Refactor Rate Limiter & test @qicz 
- [ ]  Cache Plugin integrated test @zouchangfu @qurenneng 
- [ ]  Cache Plugin Documents @zouchangfu

**Comment by qurenneng** [comment]
Cache Plugin integrated test

**Comment by zhouyadong** [comment]
Memory Cache & test
Redis Cache & test
On 03/25/2022 ***@***.***> wrote：

Description

The response data for configured requests can be cached and returned directly from the gateway next time.

Task List
Cache Plugin Module @qicz
Cache Plugin & test @qurenneng
Cache Write Plugin & test @zouchangfu
Memory Cache & test @***@***.***
Redis Cache & test @***@***.***
Refactor Rate Limiter & test @qicz
Cache Plugin integrated test @***@***.***
Cache Plugin Documents @zouchangfu
