### ISSUE TITLE
[Task] new paged list api

### ISSUE THREAD

**Issue by li-keguo** [apache/shenyu#3258]
### Description

Use the new paging method to provide more conditional searches and gradually replace the previous paging list api.

new page scheme  see https://github.com/apache/incubator-shenyu/pull/3152

### Task List

- [ ] Use the new pagination method
- [ ] Support more complex search conditions
- [ ] Provide as much information about list data as possible and associate related data
