### ISSUE TITLE
[GLCC 2022]Writing Helm Charts for ShenYu

### ISSUE THREAD

**Issue by erdengk** [apache/shenyu#3514]
### Description

Helm can help users to quickly deploy projects in Kubernetes. This project aims to write helm chart files for ShenYu.

### Task

- [ ] Complete the writing of Helm Chart
- [ ] Implement Chart's CI and Release process
- [ ] Update release documentation.

### Project technical requirements

Docker, Kubernetes, Helm

### Expected completion results

(1) Users can install ShenYu using Helm Chart
(2) Correctly implement Helm's CI and Release
(3) Complete the release documentation.

### Mentor

Kai Dang ｜ wannengdek@gmail.com

GLCC Project Link: https://www.gitlink.org.cn/glcc/subjects/detail/84
