### ISSUE TITLE
[Task][admin]  <API document enhancement: display customized headers and adds a control switch.>

### ISSUE THREAD

**Issue by lianjunwei** [apache/shenyu#3650]
### Description

Parse the swagger document and display the customized header.

### Task List

- [x] 1.Parse the swagger document and display the customized header.

The next two items are completed by another pr.
- [x] 2.Loading API documents adds a control switch, allowing users to decide whether to turn it on or off.
- [x] 3.The gateway address of the API document supports configuration in the dictionary.

The next one, another PR will be implemented.. see #3651 
- [ ] 4.API document storage strategy adjustment: from local cache to database persistence.>

**Comment by lianjunwei** [comment]
I will complete this function.
