### ISSUE TITLE
[Task] add new plugins, key-auth, basic-auth, GraphQL syntax conversion

### ISSUE THREAD

**Issue by HessTina-YuI** [apache/shenyu#3713]
### Description

add new plugins, key-auth and basic-auth
add GraphQL syntax conversion

### Task List

- [ ] key-auth @Albertsirius 
- [ ] basic-auth @rom1c77 
- [ ] GraphQL syntax conversion @rom1c77

**Comment by Albertsirius** [comment]
Please assign task 1 to me

**Comment by rom1c77** [comment]
Please assign task 2、3 to me

**Comment by HessTina-YuI** [comment]
> Please assign task 1 to me

you choose one you like
