### ISSUE TITLE
[Task] rocketmq/kafka/es log plugin client authorize field

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#3860]
### Description

 add authorize for rocketmq,kafka,es log plugin,because these clients must login.

### Task List

1. [x] add authorize field for es client @damonxue 
2. [x] add authorize field for rocketmq client @damonxue 
3. [ ] add authorize field for kafka client @misaya295

authorize field maybe include username,password, not only these.

**Comment by damonxue** [comment]
Pls assign 1 and 2 to me.

**Comment by misaya295** [comment]
Pls assign to me.

**Comment by misaya295** [comment]
> @misaya295 can you do task3? 

Yes,I can

**Comment by moremind** [comment]
> > @misaya295 can you do task3?
> 
> Yes,I can

by the way, maybe you can refactor kafka  log plugin code

**Comment by misaya295** [comment]
> > > @misaya295 can you do task3?
> > 
> > Yes,I can
> 
> by the way, maybe you can refactor kafka  log plugin code 

Ok,I will try my best.

**Comment by damonxue** [comment]
@moremind    These tasks done.

**Comment by misaya295** [comment]
@moremind hi,this task (add authorize field for kafka client) done.
