### ISSUE TITLE
[Task] add WasmPlugin to support writing plugins in other languages

### ISSUE THREAD

**Issue by dragon-zhang** [apache/shenyu#4492]
### Description

Apache ShenYu is a Java native API Gateway for service proxy, protocol conversion and API governance. Currently, ShenYu has good scalability in the Java language. However, ShenYu's support for multiple languages is still relatively weak.

The wasm bytecode is designed to be encoded in a size- and load-time-efficient binary format. WebAssembly aims to execute at native speed by taking advantage of common hardware capabilities available on a wide range of platforms.

The goal of WasmPlugin is to be able to run wasm bytecode([wasmer-java](https://github.com/wasmerio/wasmer-java) is a good choice, if you find a better choice, please discuss with me), and other languages can write ShenYu plugins based on this language(such as Rust/golang/C++) as long as they can be compiled into wasm bytecode.

More documents on wasm and WASI are as follows:
https://github.com/WebAssembly/design
https://github.com/WebAssembly/WASI

### Task List

Note: This plugin does not have client modules.
- [ ] add `shenyu-plugin-wasm` module;
- [ ] add `shenyu-integrated-test-wasm` module;
- [ ] add doc for `shenyu-plugin-wasm`;

### Relevant Skills
Know the use of Apache ShenYu, especially the plugin
Familiar with Java and another language which can be compiled into wasm bytecode

**Comment by qifanyyy** [comment]
I would like to contribute to this project on GSoC 2023. I will submit the draft proposal by today.
