### ISSUE TITLE
[Task] <tcp-proxy>

### ISSUE THREAD

**Issue by mahaitao617** [apache/shenyu#4534]
### Description
![Uploading image.png…]()

Add  tcp/upd/ws proxy function.The downstream services forwarded by our proxy service can be dynamically configured freely

### Task List
stage 1
- [ ] front design and develop
- [ ] backend crud (table discovery discovery_rel)@Redick01
- [ ] backend crud (table discovery_upstream proxy_selector)@huanccwang
- [ ] shenyu-admin(design a sql table to store tcp metadata and curd) @mahaitao617 

stage 2
- [ ] data-sync @misaya295 
- [ ] data-sync-nacos @mahaitao617 
- [ ] data-sync-consul @eurecalulu
- [ ] data-sync-websocket @wuwenrui 
- [ ] tcp plugin @ywj1352 
- [ ] testcase && doc @hudongdong129 
- [ ] Front-end and back-end joint debugging @Redick01

**Comment by ywj1352** [comment]
tcp  plugin assgin to me

**Comment by misaya295** [comment]
data-sync  assgin to me,pls

**Comment by hudongdong129** [comment]
please testcase && doc assign to me

**Comment by wuwenrui** [comment]
data-sync 我可以做（WWR）

**Comment by hudongdong129** [comment]
May I ask which class to add test cases for

**Comment by Redick01** [comment]
backend crud assgin to me

**Comment by huanccwang** [comment]
please  backend crud assgin to me

**Comment by dizent** [comment]
Is there any subdivision task you can assign to me

**Comment by choconana** [comment]
please assgin some task to me

**Comment by eurecalulu** [comment]
Please assign some task to me, thanks.

**Comment by plutokaito** [comment]
Plz assign some task to me, thx.

**Comment by Terminator111** [comment]
Please assign some task to me, thanks.

**Comment by zuobiao-zhou** [comment]
Please assign some task to me, thanks.
