### ISSUE TITLE
[Task] ShenYu sdk core test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4537]
### Description

Shenyu SDK is java sdk for java client, but shenyu sdk lost some test cases.

### Task List

1. [x] Add test case for `org.apache.shenyu.sdk.core.client.ShenyuSdkClientFactory` @omernaci 
2. [x] Add test case for `org.apache.shenyu.sdk.core.common.RequestTemplate`
3. [x] Add test case for `org.apache.shenyu.sdk.core.retry.RetryableException`
4. [x] Add test case for `org.apache.shenyu.sdk.core.util.Types`
5. [x] Add test case for `org.apache.shenyu.sdk.core.util.Util`
6. [x] Add test case for `org.apache.shenyu.sdk.core.ShenyuRequest`
7. [x] Add test case for `org.apache.shenyu.sdk.core.ShenyuResponse`

**Comment by TherChenYang** [comment]
Please assign it to me

**Comment by moremind** [comment]
> Please assign it to me

which task?

**Comment by TherChenYang** [comment]
I'll do all of these single tests，another single test task you can assign to someone else

**Comment by moremind** [comment]
> I'll do all of these single tests，another single test task you can assign to someone else

I think this task needs to be completed by the community, not a single man. And I will assign the task to you, and other tasks wait may be waiting for your pr.

**Comment by moremind** [comment]
> > I'll do all of these single tests，another single test task you can assign to someone else
> 
> I think these tasks need to be completed by the community, not a single man. And I will assign the task to you, and other tasks wait may be waiting for your pr.

**Comment by TherChenYang** [comment]
Thank you. I'll do my best

**Comment by omernaci** [comment]
Hi @moremind, if possible, can you assign me this class test `org.apache.shenyu.sdk.core.client.ShenyuSdkClientFactory`?

**Comment by omernaci** [comment]
Hi @moremind, I'm reviewing the usage of MockedStatic nowadays, can you assign me `org.apache.shenyu.sdk.core.util.Util` class?

**Comment by moremind** [comment]
> Hi @moremind, I'm reviewing the usage of MockedStatic nowadays, can you assign me `org.apache.shenyu.sdk.core.util.Util` class?

yes

**Comment by YxYL6125** [comment]
Hi, I really want to participate in the Shenyu community. Can you assign me the task ：
 - test case for org.apache.shenyu.sdk.core.ShenyuResponse
 - test case for org.apache.shenyu.sdk.core.ShenyuRequest

**Comment by YxYL6125** [comment]
if possible, i want to try rest of the task:
- `org.apache.shenyu.sdk.core.common.RequestTemplate`
- `org.apache.shenyu.sdk.core.retry.RetryableException`
- `org.apache.shenyu.sdk.core.util.Types`
