### ISSUE TITLE
[Task] ShenYu-SDK-Spring test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4538]
### Description

Add test case for `shenyu-sdk-spring` package

### Task List

1. [ ] Add test case for `CookieValueParameterProcessor`
2. [ ] Add test case for `PathVariableParameterProcessor`
3. [ ] Add test case for `RequestBodyParameterProcessor`
4. [ ] Add test case for `RequestHeaderParameterProcessor`
5. [ ] Add test case for `RequestParamParameterProcessor`
6. [ ] Add test case for `ShenyuClientInvocationHandler`
7. [ ] Add test case for `ShenyuClientMethodHandler`
8. [ ] Add test case for `ShenyuClientProxyFactory`
9. [ ] Add test case for `SpringMvcContract`
10. [ ] Add test case for `ShenyuClientFactoryBean`
11. [ ] Add test case for `ShenyuClientsRegistrar`

**Comment by damonxue** [comment]
pls assign 2 me.
