### ISSUE TITLE
[Task] ShenYu Common test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4539]
### Description

add test cases for shenyu-common package

### Task List

* dto: @comeCU 
1. [x] Add test case for `BrpcRegisterConfig` @comeCU
2. [x] Add test case for `MockHandle` @comeCU

* enums @sachin10fi
1. [x] Add test case for `TrieMatchModeEnum` @sachin10fi
4. [x] Add test case for `RuleTrieEventEnum` @sachin10fi
5. [x] Add test case for `ApiSourceEnum` @sachin10fi
6. [x] Add test case for `ApiStateEnum` @sachin10fi
7. [x] Add test case for `ApiHttpMethodEnum` @sachin10fi

* utils package: @koonchen 
1. [x] Add test case for `HmacUtils` @koonchen 
2. [x] Add test case for `JarDependencyUtils` @koonchen

**Comment by TherChenYang** [comment]
Please assign it to me

**Comment by moremind** [comment]
> Please assign it to me

which task?

**Comment by sachin10fi** [comment]
Can you please assign me the Enums' test cases task

**Comment by moremind** [comment]
> 

assigned

**Comment by koonchen** [comment]
I am a beginner with shenyu. Please assign the `utils` task to me.

**Comment by sachin10fi** [comment]
> > 
> 
> assigned

PR is raised

> > 
> 
> assigned

PR is raised https://github.com/apache/shenyu/pull/4541

**Comment by comeCU** [comment]
please assign me the dto test cases task

**Comment by moremind** [comment]
Hi, all contributors, this task has finished, and I will close this issue If you use WeChat, I will invite you to Wechat group, and my WeChat is yijia1949. Thanks for your contribution!
