### ISSUE TITLE
[Task] ShenYu Admin test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4540]
### Description

Add test cases for shenyu-admin

### Task List

* model @zuobiao-zhou 
1. [ ] Add test case for `DocParameter` @zuobiao-zhou 
2. [ ] Add test case for `UpstreamInstance` @zuobiao-zhou 

* service:
1. [x] Add test case for `DocManagerImpl` @lijay7674 
4. [x] Add test case for `LoadServiceDocEntryImpl` @lijay7674 
5. [x] Add test case for `ServiceDocManagerImpl` @lijay7674 
6. [x] Add test case for `SwaggerDocParser` @lijay7674 
7. [x] Add test case for `ShenyuClientRegisterBrpcServiceImpl` @sachin10fi 
8. [x] Add test case for `AbstractContextPathRegisterService` @sachin10fi 
9. [x] Add test case for `AbstractShenyuClientRegisterServiceImpl` @sachin10fi 
10. [x] Add test case for `FallbackShenyuClientRegisterService` @sachin10fi 
11. [x] Add test case for `ShenyuClientRegisterWebSocketServiceImpl` @sachin10fi 

* event: @whenelse 
1. [x] Add test case for `BatchPluginHandleChangedEvent` @whenelse 
2. [x] Add test case for `PluginHandleChangedEvent` @whenelse 
3. [x] Add test case for `BatchMetaDataChangedEvent` @whenelse 
4. [x] Add test case for `BatchMetaDataDeletedEvent` @whenelse 
5. [x] Add test case for `MetaDataChangedEvent` @whenelse 
6. [x] Add test case for `MetaDataCreatedEvent` @whenelse 
7. [x] Add test case for `MetadataUpdatedEvent` @whenelse 
8. [x] Add test case for `BatchPluginChangedEvent` @whenelse 
9. [x] Add test case for `BatchPluginDeletedEvent` @whenelse 
10. [x] Add test case for `PluginChangedEvent`
11. [x] Add test case for `PluginCreatedEvent`
12. [x] Add test case for `public class BatchResourceDeletedEvent extends BatchChangedEvent`
13. [x] Add test case for `BatchRoleDeletedEvent`
14. [x] Add test case for `RoleChangedEvent`
15. [x] Add test case for `RoleCreatedEvent`
16. [x] Add test case for `RoleUpdatedEvent`
17. [x] Add test case for `BatchRuleDeletedEvent`
18. [x] Add test case for `RuleChangedEvent`
19. [x] Add test case for `RuleCreatedEvent`
20. [x] Add test case for `RuleUpdatedEvent`
21. [x] Add test case for `BatchSelectorDeletedEvent`
22. [x] Add test case for `SelectorChangedEvent`
23. [x] Add test case for `SelectorCreatedEvent`
24. [x] Add test case for `SelectorUpdatedEvent`
25. [x] Add test case for `BatchUserDeletedEvent`
26. [x] Add test case for `UserChangedEvent`
27. [x] Add test case for `UserCreatedEvent`
28. [x] Add test case for `UserUpdatedEvent`

* utils
1. [x] Add test case for `HttpUtils` @hudongdong129

**Comment by hudongdong129** [comment]
please  Assign this task to me for Add test case for HttpUtils

**Comment by moremind** [comment]
> please Assign this task to me for Add test case for HttpUtils

assigned

**Comment by zuobiao-zhou** [comment]
please assign the task of add test case for model.

**Comment by moremind** [comment]
> please assign the task of add test case for model.

assigned

**Comment by lijay7674** [comment]
I want to try to complete these tasks,please Assign this task to me for Add test case for service

**Comment by moremind** [comment]
> I want to try to complete these tasks,please Assign this task to me for Add test case for service

which task?

**Comment by lijay7674** [comment]
> 

The first four of the service

**Comment by moremind** [comment]
> > 
> 
> The first four of the service

assigned

**Comment by lijay7674** [comment]
> > > 
> > 
> > 
> > The first four of the service
> 
> assigned

I'm sorry, accidentally click wrong

**Comment by sachin10fi** [comment]
Can you please assign me the rest of the service classes

**Comment by moremind** [comment]
> Can you please assign me the rest of the service classes

assigned

**Comment by omernaci** [comment]
Hi @moremind, I would happy to contribute for `PluginChangedEvent` and `PluginCreatedEvent` classes tests.

**Comment by devinsong77** [comment]
hi @moremind，can you assign the task add test case for `BatchRoleDeletedEvent` , `RoleChangedEvent`, `RoleCreatedEvent`, `RoleUpdatedEvent` to me, thank you

**Comment by moremind** [comment]
> hi @moremind，can you assign the task add test case for `BatchRoleDeletedEvent` , `RoleChangedEvent`, `RoleCreatedEvent`, `RoleUpdatedEvent` to me, thank you

assigned

**Comment by moremind** [comment]
> hi, @moremind, please assign `BatchRuleDeletedEvent、RoleChangedEvent、RoleCreatedEvent、RoleUpdatedEvent、BatchSelectorDeletedEvent、SelectorChangedEvent、SelectorCreatedEvent、SelectorUpdatedEvent `for me , thanks.

assigned,

**Comment by whenelse** [comment]
please Assign this task to me for Add test case for PluginChangedEvent and PluginCreatedEvent

**Comment by whenelse** [comment]
hi, @moremind, please assign `BatchPluginHandleChangedEvent`、`PluginHandleChangedEvent`、`BatchPluginChangedEvent`、`BatchPluginDeletedEvent` for me , thanks.

**Comment by moremind** [comment]
> hi, @moremind, please assign `BatchPluginHandleChangedEvent`、`PluginHandleChangedEvent`、`BatchPluginChangedEvent`、`BatchPluginDeletedEvent` for me , thanks.

assigned

**Comment by whenelse** [comment]
hi, @moremind also need to assign the above PluginChangedEvent and PluginCreatedEvent

**Comment by whenelse** [comment]
please assign all event tasks to me, thanks

**Comment by moremind** [comment]
> please assign all event tasks to me, thanks

assigned
