### ISSUE TITLE
[Task] ShenYu client core test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4544]
### Description

Add test case for shenyu-client-core

### Task List

1. [ ] Add test case for `AbstractContextRefreshedEventListener` @strawberry-crisis 
2. [ ] Add test case for `RegisterClientConsumerExecutor`
3. [x] Add test case for `ShenyuClientApiDocExecutorSubscriber` @omernaci 
4. [x] Add test case for `ShenyuClientMetadataExecutorSubscriber` @yunuskarakaya 
5. [ ] Add test case for `ShenyuClientURIExecutorSubscriber`
6. [ ] Add test case for `ShenyuClientRegisterEventPublisher`
7. [x] Add test case for `ShenyuClientIllegalArgumentException`
8. [ ] Add test case for `ShenyuClientRegisterRepositoryFactory`
9. [ ] Add test case for `ShenyuClientShutdownHook`
10. [x] Add test case for `PortUtils` @VampireAchao

**Comment by strawberry-crisis** [comment]
Can I help with AbstractContextRefreshedEventListener? Thanks.

**Comment by VampireAchao** [comment]
[add test case for PortUtils.findPort](https://github.com/apache/shenyu/pull/4604)

**Comment by omernaci** [comment]
Hi @moremind,  I would happy to contribute for `ShenyuClientApiDocExecutorSubscriber` class test.

**Comment by moremind** [comment]
> Hi @moremind, I would happy to contribute for `ShenyuClientApiDocExecutorSubscriber` class test.

assigned

**Comment by strawberry-crisis** [comment]
> Can I help with AbstractContextRefreshedEventListener? Thanks.

Sorry for the delay. Actually, I am not familiar with writing JUnit tests for an abstract class. Are there any examples that I can reference?

**Comment by moremind** [comment]
> > Can I help with AbstractContextRefreshedEventListener? Thanks.
> 
> Sorry for the delay. Actually, I am not familiar with writing JUnit tests for an abstract class. Are there any examples that I can reference?

yes, of course, please see shenyu-client

**Comment by omernaci** [comment]
If it's suitable, I could also write a test for this class `ShenyuClientMetadataExecutorSubscriber`.

**Comment by yunuskarakaya** [comment]
hi @moremind,  I would like write a test for this class `ShenyuClientMetadataExecutorSubscriber`.

**Comment by Divyansh200102** [comment]
Hi, I would like to writ the test for `ShenyuClientMetadataExecutorSubscriber`

**Comment by Divyansh200102** [comment]
@dragon-zhang @moremind  please review #5404 #5406

**Comment by Aias00** [comment]
Hi, @moremind  I would like to write the test for ShenyuClientURIExecutorSubscriber

**Comment by Aias00** [comment]
> Hi, @moremind I would like to write the test for ShenyuClientURIExecutorSubscriber

@moremind  please review https://github.com/apache/shenyu/pull/5413

**Comment by L7L9** [comment]
Hi, @moremind i want to contribute for `RegisterClientConsumerExecutor` class test

**Comment by kamiingithub** [comment]
Hi @moremind, I would happy to contribute for RegisterClientConsumerExecutor class test. thx.
