### ISSUE TITLE
[Task] shenyu-client-grpc test case

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4545]
### Description

Add test case for `shenyu-client-grpc`

### Task List

1. [ ] Add test case for `JsonForwardingServerCall`
2. [ ] Add test case for `JsonServerCallListener`
3. [ ] Add test case for `JsonServerServiceInterceptor`
4. [ ] Add test case for `GrpcServerRunner`
5. [ ] Add test case for `GrpcClientEventListener`

**Comment by dev-ST-IA** [comment]
Hello, I would like to try this, can I attempt this? if so please assign it to me, I'll try to complete it
