### ISSUE TITLE
[Task] Refactors the collection of client registration information

### ISSUE THREAD

**Issue by tian-pengfei** [apache/shenyu#4560]
## Description

​		`AbstractContextRefreshedEventListener` is too coupled, which makes it difficult to scale. Therefore  we need to redesign the collection of client registration information . 

​		Various types of API (eg:`Api-Doc`,`Api-Meta`)collections are coupled together in `AbstractContextRefreshedEventListener`,so we mainly need to refactor the design of API-related information collection.

## Aims
+ It supports to register api without annotations
+ You can customize the registration mode with it
+ The hierarchies  will changes from inheritance to composition.
+ API information generation rules  will be customizable，which mean it can independent of annotations.
+ You can custom API matching rules to decide what kind of API meets the requirements.
+ Spring-Boot Client will support Automatic configuration.
+ It will be a non-invasive design,which don't influence the old design.

## Design

![new design](https://github.com/apache/shenyu/assets/42602026/5848b91d-2340-44cb-bb92-744d496f28c0)

## Task

- [x]  initializes base design                                  [tian-pengfei](https://github.com/tian-pengfei)
         #4566
        #4724
- [x]  initializes spring-boot auto config              [tian-pengfei](https://github.com/tian-pengfei) 
         #4583
        #4724
- [x]  support spring-mvc (boot )                         [tian-pengfei](https://github.com/tian-pengfei) 
         #4600 
         #4615
        #4724
- [ ]  support spring-mvc (no boot)                     [tian-pengfei](https://github.com/tian-pengfei) 
- [ ]  support spring-cloud 
        #4737
- [ ]  support spring-dubbo
- [ ]  support eureka
- [ ]  support tars
- [ ]  support sofa 
- [ ]  support  motan
- [ ]  support  grpc
- [ ]  support  brpc
- [ ] add Integration-tests

**Comment by dragon-zhang** [comment]
Suggest writing examples and integration tests.

**Comment by tian-pengfei** [comment]
> Can `ApiBean` add comment from javadoc comment? With https://github.com/dnault/therapi-runtime-javadoc , it can be done.

I think its great idea, I will think about it ,thank your advice. may be we can do it  together.

**Comment by dragon-zhang** [comment]
> > Can `ApiBean` add comment from javadoc comment? With https://github.com/dnault/therapi-runtime-javadoc , it can be done.
> 
> I think its great idea, I will think about it ,thank your advice. may be we can do it together.

sure
