### ISSUE TITLE
[Task] ShenYu e2e refactor

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#4671]
### Description

ShenYu e2e module needs to refactor at present, refactor the code support shenyu check style.

### Task List

1. [ ] refactor shenyu e2e engine code support shenyu check style
2. [ ] refactor shenyu e2e common code support shenyu check style
3. [ ] refactor shenyu e2e client code support shenyu check style
4. [ ] refactor shenyu case engine code support shenyu check style

**Comment by omernaci** [comment]
Hi @moremind, I would happy to refactor `shenyu-e2e-engine` with shenyu-check-style.

**Comment by moremind** [comment]
> Hi @moremind, I would happy to refactor `shenyu-e2e-engine` with shenyu-check-style rules.

Hi, @omernaci , I have assigned this task to you.

**Comment by runqi-zhao** [comment]
Hi @moremind, I would happy to refactor `shenyu-e2e-common` with shenyu-check-style rules.

**Comment by moremind** [comment]
@runqi-zhao I have assigned this task to you.

**Comment by Albertsirius** [comment]
Hi, I would like to try "refactor shenyu e2e client code support shenyu check style" task. please assign to me

**Comment by moremind** [comment]
> Hi, I would like to try "refactor shenyu e2e client code support shenyu check style" task. please assign to me

ok

**Comment by arenick001** [comment]
Hi @moremind ,I would like to try the remaining task，but I don't know witch one remains. @omernaci said he wanted to refactor shenyu-e2e-engine but you assigned shenyu-case-engine to him.

**Comment by damonxue** [comment]
Hi, @moremind pls assign task 1 to me. Thank u.

**Comment by damonxue** [comment]
pls assign 2 me.

**Comment by moremind** [comment]
@omernaci @runqi-zhao @Albertsirius Hi, this task is overtime, I will reassign it to @damonxue
