### ISSUE TITLE
[Task] Client Active Offline

### ISSUE THREAD

**Issue by loongs-zhang** [apache/shenyu#4686]
### Description

Currently, shenyu only supports passive offline, during which the front-end will have a clear perception (i.e. response 408), indicating that it is better to support active offline.

The idea is roughly:
1. The client utilizes the mechanism provided by `ShenyuClientShutdownHook` to call the offline interface of shenyu admin;
2. In the offline interface of shenyu admin, we update the database and send events;

### Task List

- [x] springmvc client
- [x] ~~spring cloud client wait for https://github.com/apache/shenyu/issues/4680~~
- [ ] springmvc client active offline support shenyu-admin cluster
- [x] ZookeeperClientRegisterRepository active offline @xuziyang
- [x] NacosClientRegisterRepository active offline @847850277 
- [x] EtcdClientRegisterRepository active offline @xuziyang
- [x] ConsulClientRegisterRepository active offline @847850277 
- [x] ApolloClientRegisterRepository active offline @xuziyang

**Comment by weiweily** [comment]
hello， when this will be ok？

**Comment by dragon-zhang** [comment]
> hello， when this will be ok？

At least 2.6.0.

**Comment by dragon-zhang** [comment]
After discuss, we think the spring cloud active offline is not needed.

**Comment by xuziyang** [comment]
I would like to take on this job.

**Comment by 847850277** [comment]
please asign  `ConsulClientRegisterRepository active offline` and `  NacosClientRegisterRepository active offline` to me.

**Comment by xuziyang** [comment]
please asign  ApolloClientRegisterRepository active offline to me.

**Comment by loongs-zhang** [comment]
see https://github.com/apache/shenyu/issues/5324

**Comment by loongs-zhang** [comment]
https://github.com/apache/shenyu/issues/5324
