### ISSUE TITLE
[Task] RewritePlugin supports cross application

### ISSUE THREAD

**Issue by loongs-zhang** [apache/shenyu#4687]
### Description

Currently, RewritePlugin only supports rewrite url in the same application, this task needs RewritePlugin to supports rewrite url cross applications which accessed in shenyu.

### Task List

- [ ] refactor RewritePlugin to support URL rewriting across applications.
- [x] support adjusting traffic percentage, default to 100% to ensure compatibility with older versions.
- [ ] refactor RewritePlugin to support URL rewriting across plugins.

**Comment by December-Pb** [comment]
Hi,
I'd like to take this task, but before that, I have two questions: 
1. What is the RewritePlugin for?
2. What is the definition of "application" in this context?

**Comment by dragon-zhang** [comment]
For Q1: see https://shenyu.apache.org/docs/next/plugin-center/http-process/rewrite-plugin

For Q2: `Application` refers to an application that is proxied by shenyu-gateway, just like [shenyu-examples-http](https://github.com/apache/shenyu/tree/master/shenyu-examples/shenyu-examples-http)

**Comment by dragon-zhang** [comment]
> Hi, I'd like to take this task, but before that, I have two questions:
> 
> 1. What is the RewritePlugin for?
> 2. What is the definition of "application" in this context?

For Q1: see https://shenyu.apache.org/docs/next/plugin-center/http-process/rewrite-plugin

For Q2: `Application` refers to an application that is proxied by shenyu-gateway, just like [shenyu-examples-http](https://github.com/apache/shenyu/tree/master/shenyu-examples/shenyu-examples-http)

**Comment by December-Pb** [comment]
Hi,
Thanks for the explanation. After reading the blog, I have several follow up questions.
First of all, there are several links which are not accessible. 
https://shenyu.apache.org/docs/next/plugin-center/user-guide/admin-usage/selector-and-rule
https://shenyu.apache.org/docs/next/plugin-center/quick-start/quick-start-http#run-the-shenyu-examples-http-project

I have a general idea on what's the work of rewrite-plugin: it can help the customer to replace the sub-url to other string. For example: after opening the rewrite plugin, we can replace the `http://localhost:9095/http/hello` to `http://localhost:9095/hi`
1. Is this what the rewrite does? Do I miss any other functions of rewrite plugin?
2. Do we have any real world example on the use of this plugin? It's hard for me to come up with one.
3. What is the real world example of this task - support rewriting the url cross different application?
4. How can we support rewriting the url cross different application? I didn't find how we differentiate the url from different application in the [doExecute](https://github.com/apache/shenyu/blob/2832b8f9cf9e051a77cc5184290ba83ea7dae9f8/shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java#L47) method.
5. I noticed in the task list, you mentioned "support adjusting traffic percentage", how are we going to achieve that?

Sorry for so many questions, I just want to clarify everything before the implementation.

**Comment by dragon-zhang** [comment]
> First of all, there are several links which are not accessible. https://shenyu.apache.org/docs/next/plugin-center/user-guide/admin-usage/selector-and-rule https://shenyu.apache.org/docs/next/plugin-center/quick-start/quick-start-http#run-the-shenyu-examples-http-project

About links problem, can you fix them in [shenyu-website](https://github.com/apache/shenyu-website) ?

> For example: after opening the rewrite plugin, we can replace the http://localhost:9095/http/hello to http://localhost:9095/hi
> 1.Is this what the rewrite does? Do I miss any other functions of rewrite plugin?

yes

> 2.Do we have any real world example on the use of this plugin? It's hard for me to come up with one.
> 3.What is the real world example of this task - support rewriting the url cross different application?

Assuming you originally had one application that needed to be `split into many applications` due to increasingly complex business, there would be a need for interface flow switching, and RewritePlugin would come in handy.

> 4.How can we support rewriting the url cross different application? I didn't find how we differentiate the url from different application in the [doExecute](https://github.com/apache/shenyu/blob/2832b8f9cf9e051a77cc5184290ba83ea7dae9f8/shenyu-plugin/shenyu-plugin-rewrite/src/main/java/org/apache/shenyu/plugin/rewrite/RewritePlugin.java#L47) method.

Tracking `Constants.REWRITE_URI`, `RewritePlugin` just put the attritube, use the attritube is in `AbstractHttpClientPlugin#resend`.

> 5.I noticed in the task list, you mentioned "support adjusting traffic percentage", how are we going to achieve that?

In `RewritePlugin`, the `handle`, we need to add a `percentage`(default 100) field, the percentage` can be changed in `shenyu-admin`, and the `RewritePlugin` use `percentage` to decide whether to put `Constants.REWRITE_URI`.

**Comment by December-Pb** [comment]
I‘ve [updated the doc](https://github.com/apache/shenyu-website/commit/b28c8314425f47dc9f55fddde276c9e80e1e9cea), the latest doc link should be `https://shenyu.apache.org/docs/plugin-center/http-process/rewrite-plugin/` rather than `https://shenyu.apache.org/docs/next/plugin-center/http-process/rewrite-plugin`

I read through the code base and find [here](https://github.com/apache/shenyu/blob/907e34ebcabe4289d1949d0740df77afc7af649b/shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java#L155)(`final URI newUri = RequestUrlUtils.buildRequestUri(exchange, upstream.buildDomain());`) we get the new URI which has already been rewritten. So can I assume after this step we finished the work of the `RewritePlugin`?

My Question is:
1. Can I assume each URI represent an application?
2. What does the URI look like when there are several applications? And what does the URI look like after the rewrite? Could you provide an example?

**Comment by dragon-zhang** [comment]
> I‘ve [updated the doc](https://github.com/apache/shenyu-website/commit/b28c8314425f47dc9f55fddde276c9e80e1e9cea), the latest doc link should be https://shenyu.apache.org/docs/plugin-center/http-process/rewrite-plugin/ rather than https://shenyu.apache.org/docs/next/plugin-center/http-process/rewrite-plugin

good job !

> I read through the code base and find [here](https://github.com/apache/shenyu/blob/907e34ebcabe4289d1949d0740df77afc7af649b/shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java#L155)(final URI newUri = RequestUrlUtils.buildRequestUri(exchange, upstream.buildDomain());) we get the new URI which has already been rewritten. So can I assume after this step we finished the work of the RewritePlugin?

Not just `RewritePlugin`, the other usages like below should be all changed.
![image](https://github.com/apache/shenyu/assets/38336731/bd37959d-a11a-486e-8b7f-df6cdc763569)

> Can I assume each URI represent an application?
> What does the URI look like when there are several applications? And what does the URI look like after the rewrite? Could you provide an example?

`shenyu-examples-http` had provide servers such as `/http/order/**`(In `OrderController`) and `/http/upload/**`(In `UploadController`).

Now we need to add 2 projects to replace `shenyu-examples-http`, which named `shenyu-examples-http-order` and `shenyu-examples-http-upload`.

The original `/http/order/**` needs to be rewritten as `/http-order/order/**`, then the traffic can linked to `shenyu-examples-http-order`(not the original `shenyu-examples-http` project). 

The same actions needs to be done like `shenyu-examples-http-upload`.

Can you add my wechat `Z18179469818` ?

**Comment by lianjunwei** [comment]
ISSUE https://github.com/apache/shenyu/issues/4923 , I have a suggestion to adjust the execution order of the plugins.
This change will increase the priority of the rewrite plugin, which may cause external users' URLs to bypass the authentication plugin.
