### ISSUE TITLE
[Task] <apidoc enhance and optimize. >

### ISSUE THREAD

**Issue by lianjunwei** [apache/shenyu#4848]
### Description

The field splitting of apidoc details API, as well as the enhancement and optimization of swigger apidoc.

### Task List

- [x] 1.Storage adjustment for swagger type API documents: change from local cache to database. @lianjunwei #4849
- [x] 2.To simplify front-end development, the "document" field of the detailed interface of apidoc is disassembled, add requestHeaders, responseParameters, and more.  @lianjunwei #4865 
- [x] 3.add document in shenyu-website @lianjunwei 
- [x] 4.Add swagger sample project. @lianjunwei #4824  #4825
- [x] 5.Performance optimization: If there are no changes in apidoc, there is no need to update the database. @lianjunwei #4860 
- [x] 6.Some fixes and optimizations related to apidoc, as well as adjustments to the Swagger example project. #4891

_No response_
