### ISSUE TITLE
[Task] Adding a Motan plugin 、Spring Cloud and WebSocket plugin to shenyu ingress-controller

### ISSUE THREAD

**Issue by runqi-zhao** [apache/shenyu#5053]
### Description

see https://github.com/apache/shenyu/issues/4581 https://github.com/apache/shenyu/issues/4438

### Task List

- [x] Adding a Motan plugin to shenyu ingress-controller
- [x]  Support for Motan TLS configuration
- [x] Adding a Spring Cloud plugin to shenyu ingress-controller
- [x] Support for Spring Cloud TLS configuration
- [x] Adding a WebSocket plugin to shenyu ingress-controller
- [x] Adding a WebSocket plugin to shenyu ingress-controller
