### ISSUE TITLE
[Task] Apache ShenYu 2.6.1 Release Task

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5350]
### Description

After 4 months of continuous updates, Apache ShenYu 2.6.1 will be released. Now we must finish these tasks as follows before the release time.

### Task List

1. [x] Check the license and dependency
2. [x] Publish the document of 2.6.1
3. [x] Fix the remaining bugs
