### ISSUE TITLE
[Task] shenyu-plugin-wasm-base module test case

### ISSUE THREAD

**Issue by loongs-zhang** [apache/shenyu#5427]
### Description

Add test case for `shenyu-plugin-wasm-base`.

You can refer to `shenyu-plugin/shenyu-plugin-wasm-base/src/test/java/org/apache/shenyu/plugin/wasm/base/AbstractWasmPluginTest.java` and `shenyu-plugin/shenyu-plugin-wasm-base/src/test/README.md`.

BTW, you can use another language, as long as they can be compiled into WASM bytecode. Please remember to add a `README.md` that explains how to convert the source code to WASM.

Does anyone want to try it?

### Task List

1. [x] Add test case for `AbstractShenyuWasmPlugin`
2. [x] Add test case for `AbstractWasmDiscoveryHandler` @Divyansh200102
3. [ ] Add test case for `AbstractWasmMetaDataHandler`
4. [x] Add test case for `AbstractWasmPluginDataHandler`

**Comment by Divyansh200102** [comment]
I would like to try for `AbstractWasmDiscoveryHandler`

**Comment by Divyansh200102** [comment]
I would like to try for `AbstractWasmDiscoveryHandler`

**Comment by Divyansh200102** [comment]
I would like try for `AbstractWasmDiscoveryHandler`

**Comment by Divyansh200102** [comment]
I would like to try for `AbstractWasmDiscoveryHandler`

**Comment by Divyansh200102** [comment]
@dragon-zhang could you please tell what all things I should be familiar with to work on this.

**Comment by dragon-zhang** [comment]
Rust experience with WASM, although Rust is difficult, following the steps in the document shall be fine.


Docs in https://shenyu.apache.org/docs/next/developer/custom-plugin
Single Responsibility Plugin in Multiple Languages



I also write docs for Dubbo, see https://github.com/apache/dubbo-spi-extensions/pull/285/files#diff-148b5a5f8d047f18a92b882112faf592114871cc67b971662b7ffc56d5f02b34
---- Replied Message ----
| From | ***@***.***> |
| Date | 02/5/2024 17:18 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [apache/shenyu] [Task] shenyu-plugin-wasm-base module test case (Issue #5427) |

@dragon-zhang could you please tell what all things I should be familiar with to work on this.

**Comment by Divyansh200102** [comment]
> Rust experience with WASM, although Rust is difficult, following the steps in the document shall be fine.
> 
> 
> Docs in https://shenyu.apache.org/docs/next/developer/custom-plugin
> Single Responsibility Plugin in Multiple Languages
> 
> 
> 
> I also write docs for Dubbo, see https://github.com/apache/dubbo-spi-extensions/pull/285/files#diff-148b5a5f8d047f18a92b882112faf592114871cc67b971662b7ffc56d5f02b34
> ---- Replied Message ----
> | From | ***@***.***> |
> | Date | 02/5/2024 17:18 |
> | To | ***@***.***> |
> | Cc | ***@***.***> ,
> ***@***.***> |
> | Subject | Re: [apache/shenyu] [Task] shenyu-plugin-wasm-base module test case (Issue #5427) |
> 
> @dragon-zhang could you please tell what all things I should be familiar with to work on this.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

Okay thank you @dragon-zhang

**Comment by Divyansh200102** [comment]
@dragon-zhang  could you please check the mail I sent you from divyanshkhatri999@gmail.com I sent it to this mail id (1936978077@qq.com)

**Comment by Divyansh200102** [comment]
In the documentation  the `doExecute` method is not given which is needed for the the building the plugin for `AbstractShenyuWasmPlugin` so how do I proceed from here?

![image](https://github.com/apache/shenyu/assets/146909065/b33be748-3d0f-4c76-9a26-18a6b12cb14d)

**Comment by Divyansh200102** [comment]
Sorry for the trouble @loongs-zhang 
In the documentation WASM section of `Matching Traffic Processing Plugin in Multiple Languages` the `doExecute` method is not implemented in rust which is needed for building the plugin for `shenyu-plugin-wasm-base`  
![image](https://github.com/apache/shenyu/assets/146909065/27675a7c-1e1b-4e60-800f-ebbdf66dac66)
but in case of `Single Responsibility Plugin in Multiple Languages` which had the `execute` method it was provided in the documentaion.

```rust
#[no_mangle]
pub unsafe extern "C" fn execute(arg_id: i64) {
    let mut buf = [0u8; 32];
    let buf_ptr = buf.as_mut_ptr() as i64;
    eprintln!("rust side-> buffer base address: {}", buf_ptr);
    // get arg from java
    let len = get_args(arg_id, buf_ptr, buf.len() as i32);
    let java_arg = std::str::from_utf8(&buf[..len as usize]).unwrap();
    eprintln!("rust side-> recv:{}", java_arg);
    // pass rust result to java
    let rust_result = "rust result".as_bytes();
    let result_ptr = rust_result.as_ptr() as i64;
    _ = put_result(arg_id, result_ptr, rust_result.len() as i32);
}
``` 
So could you please tell how am I supposed to proceed from here?

**Comment by loongs-zhang** [comment]
Sorry, I will reply to you in a few days. I am still celebrating the Chinese New Year.

**Comment by Divyansh200102** [comment]
> Sorry, I will reply to you in a few days. I am still celebrating the Chinese New Year.

Ofcourse,Happy lunar new year!

**Comment by loongs-zhang** [comment]
The method name of Java calling WASM depends on the definition of the abstract class. More importantly, we use `org.apache.shenyu.plugin.wasm.api.loader.WasmLoader#getWasmExtern` to obtain the WASM function. So you can see the names below:

For `AbstractWasmPlugin`, see `AbstractWasmPlugin#EXECUTE_METHOD_NAME`;

For `AbstractShenyuWasmPlugin`, see `AbstractShenyuWasmPlugin#DO_EXECUTE_METHOD_NAME`;
@Divyansh200102

**Comment by Divyansh200102** [comment]
> The method name of Java calling WASM depends on the definition of the abstract class. More importantly, we use `org.apache.shenyu.plugin.wasm.api.loader.WasmLoader#getWasmExtern` to obtain the WASM function. So you can see the WASM function names(that's why are the rust functions named these names) below:

I think I wasn't able to convey my message properly I do understand why the rust functions are named the way they are but I was asking that in `shenyu-plugin/shenyu-plugin-wasm-api/src/test/rust-wasm-plugin/src/lib.rs` in `lib.rs` the `execute` method which is written in rust and was used for making plugin(`rust-wasm-plugin`) for `AbstractWasmPlugin`
```rust
#[no_mangle]
pub unsafe extern "C" fn execute(arg_id: i64) {
    let mut buf = [0u8; 32];
    let buf_ptr = buf.as_mut_ptr() as i64;
    eprintln!("rust side-> buffer base address: {}", buf_ptr);
    // get arg from java
    let len = get_args(arg_id, buf_ptr, buf.len() as i32);
    let java_arg = std::str::from_utf8(&buf[..len as usize]).unwrap();
    eprintln!("rust side-> recv:{}", java_arg);
    // pass rust result to java
    let rust_result = "rust result".as_bytes();
    let result_ptr = rust_result.as_ptr() as i64;
    _ = put_result(arg_id, result_ptr, rust_result.len() as i32);
}
``` 
was taken from here in the documentation

![image](https://github.com/apache/shenyu/assets/146909065/2f876b72-43c9-4afa-bbed-4df4a66a49c3)

so I am asking that if i want to make the plugin for `AbstractShenyuWasmPlugin` I need the `doexecute` method in rust to put in my `lib.rs` but it's not given in the documentation

![image](https://github.com/apache/shenyu/assets/146909065/4aedc4c6-621b-4d2c-8372-53ab7b43cdbf)

so I should I proceed from here? @loongs-zhang

**Comment by Divyansh200102** [comment]
@loongs-zhang Could you please take a look at #5451 and #5452 give your review

**Comment by Divyansh200102** [comment]
@loongs-zhang Could you please take a look at #5451 , #5452 and #5453 and tell if there any changes needed or any mistakes?
