### ISSUE TITLE
[Task] ShenYu Admin Cluster

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5448]
### Description

As ShenYu is popular, ShenYu Gateway has supported cluster mode(shenyu-nginx, nginx, and so on), But ShenYu Admin does not support cluster mode, we need to design admin cluster mode.

### Task List

1. [x] Design shenyu admin cluster model
2. [x] Admin distributed  lock by spring-integration-mysql @crudboy 
3. [x] Implement ShenYu admin cluster model
4. [x] Add e2e shenyu admin cluster test case

**Comment by crudboy** [comment]
Admin distributed lock by spring-integration-mysql pls assigne me .

**Comment by wlngo** [comment]
Implement ShenYu admin cluster model   I  want to try it.

**Comment by Aias00** [comment]
> Implement ShenYu admin cluster model I want to try it.

can u add my wechat : aias00

**Comment by wlngo** [comment]
> > 实现神宇管理员集群模型我想尝试一下。
> 
> 可以加我微信吗：aias00
ok ,I've added.
