### ISSUE TITLE
[Task] Enhance metrics plugin

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5449]
### Description

ShenYu metrics plugin just collect simple data, we need to trace rate-limit and circuit-breaker including ratelimiter-plugin, hystrix plugin, sentinel plugin

### Task List

1. [x] ratelimiter plugin @moremind 
2. [x] hystrix plugin @GNK48-Ava 
3. [x] sentinel plugin @GNK48-Ava 
4. [x] resilience4j plugin @GNK48-Ava

**Comment by fabian4** [comment]
I can help with this one

**Comment by GNK48-Ava** [comment]
I am willing to give it a try. Please assign me a task ~ @moremind

**Comment by vigneshreddy17** [comment]
Hi, I am interested to pick this one, but can you please give a brief regarding that exactly are we expecting from this " we need to trace rate-limit and circuit-breaker".

**Comment by moremind** [comment]
these tasks have finished
