### ISSUE TITLE
[Task] <Upgrade apache dubbo version support>

### ISSUE THREAD

**Issue by tomsun28** [apache/shenyu#5523]
### Description

Now we support apache dubbo 2.x version. We need to upgrade the dubbo version 3.x to meet java17 compatible.  

now

```
<apache.dubbo.version>2.7.15</apache.dubbo.version>
```

please make sure this can running with java17 jdk

### Task List

- [ ] Upgrade apache dubbo version support
- [ ] Upgrad and test pass in shenyu-examples/shenyu-examples-dubbo shenyu-examples/shenyu-examples-sdk 
- [ ] Upgrad and test pass in shenyu-integrated-test/shenyu-integrated-test-apache-dubbo  shenyu-integrated-test/shenyu-integrated-test-k8s-ingress-apache-dubbo

**Comment by Aias00** [comment]
assign me , pls
