### ISSUE TITLE
[Task]  Add end-to-end (E2E) testing for logging plugins.

### ISSUE THREAD

**Issue by xcsnx** [apache/shenyu#5529]
### Description

Currently, there are many logging plugins in Shenyu that lack end-to-end (E2E) testing. It is necessary to improve the E2E testing for these logging plugins now. You can refer to the E2E testing of the RocketMQ logging plugin: https://github.com/apache/shenyu/pull/5439

### Task List

- [ ] 1. Logging-ElasticSearch Plugin
- [ ] 2. Logging-RabbitMq Plugin
- [ ] 3. Logging-Kafka Plugin
- [ ] 4 .Logging-Pulsar Plugin
- [ ] 5. Logging-Clickhouse Plugin
- [ ] 6. Logging-RocketMq Plugin (Finished)

**Comment by RayayChung** [comment]
pls assign logging-kafka to me

**Comment by Divyansh200102** [comment]
I would like to try

**Comment by HsiuChi** [comment]
Please assign part 1,2 to me

**Comment by ling0900** [comment]
Please assign one or more to me, I would like to do

**Comment by zzzk1** [comment]
Hi @xcsnx, can you assign `Logging-Kafka Plugin` part to me?

**Comment by xcsnx** [comment]
> Hi @xcsnx, can you assign `Logging-Kafka Plugin` part to me?

Certainly, but it seems that someone has already attempted to work on Kafka, yet there are still some issues. If you're interested, you can build upon their work to achieve the goal. For more details, please refer to the PR: https://github.com/apache/shenyu/pull/5540.

**Comment by 478320** [comment]
pls assign part 2 to me

**Comment by kamiingithub** [comment]
Hi @xcsnx, pls assign part 1 and 5 to me

**Comment by no-regret666** [comment]
Hello, @xcsnx ,i would like to try part 1,can you assign it to me?

**Comment by xcsnx** [comment]
> Hello, [@xcsnx](https://github.com/xcsnx) ,i would like to try part 1,can you assign it to me?


of course

**Comment by wjwang00** [comment]
Hi @xcsnx ,If Task 4: Logging-Pulsar Plugin is not yet completed, I would like to try to finish it.

**Comment by SouthwestAsiaFloat** [comment]
Hello @xcsnx ,if task 5 is not assigned at present, I'd like to take this task. Very appreciate if you could let me have this on me 😊
