### ISSUE TITLE
[Task] Verify ShenYu Bootstrap data consistency

### ISSUE THREAD

**Issue by moremind** [apache/shenyu#5556]
### Description

shenyu admin will support cluster mode, and shenyu bootstrap has been supported, but shenyu-bootstrap cannot guarantee consistent data from every bootstrap node, so shenyu community will develop to support it.

### Task List

1. [ ] get endpoint from bootstrap by admin
2. [ ] check the bootstrap node consistency
3. [ ] if bootstrap node data not right, resycn data

**Comment by Aias00** [comment]
i can do that, assign me pls

**Comment by WindSearcher** [comment]
can u add my wechat:windsearcher？i have some problems
