### ISSUE TITLE
[type:refactor]Decouple apidoc module from rule and selector modules

### ISSUE THREAD

**Issue by 478320** [apache/shenyu#5684]
### Description

decouple apidoc module from rule and selector modules, link https://github.com/apache/shenyu/issues/5623

Make sure that:

### Task List

 - [X] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
 - [X] You submit test cases (unit or integration tests) that back your changes.
 - [X] Your local test passed ./mvnw clean install -Dmaven.javadoc.skip=true.
